### ISSUE TITLE
No module named 'extensions.layers.nms.src.cython_nms'

### ISSUE THREAD

**Issue by DNALuo** [donnyyou/torchcv#1]
Hi,

Great job! It is a great framework to learn pytorch and latest networks.

But when I am training the openpose network, it shows No module named 'extensions.layers.nms.src.cython_nms'. And I check with the files, finding the file is missing.

Is there anything I am missing?

**Comment by youdonny** [comment]
Run 'make' in the PyTorchCV directory to build Cython scripts. But I am not sure OpenPose could be trained successfully, because I have refactored the code many times. And I will update it as soon as possible! Please keep your continuous attention!

**Comment by youdonny** [comment]
Now you can use the detection and classification and segmentation methods.

**Comment by DNALuo** [comment]
Thanks for your help!
After 'make' in the root path, there is still an issue about pycocotools. It shows

`ModuleNotFoundError: No module named 'pycocotools'`

But after I 'make' under the PythonAPI directory as the readme says, it is still there. Do you have any idea?

And if you could help with all the file holders needing 'make', it would help a lot.

solved:
under PythonAPI directory,
`python3 setup.py install`

New issue:
using
`python main.py --hypes hypes/pose/coco/op_vgg19_coco_pose.json --base_lr 0.001 --phase train --gpu 0`
Then it shows
`'OpenPose' object has no attribute 'module'`
Any idea?

**Comment by youdonny** [comment]
I will update OpenPose this week.

**Comment by DNALuo** [comment]
Ok.
