### ISSUE TITLE
yolov3 loss error

### ISSUE THREAD

**Issue by iGuaZi** [donnyyou/torchcv#10]
in utils/layers/det/yolo_detection_layer.py :
I believe line 42(if self.configer.get('phase') != 'debug':) should be removed,
because values passed to BCE loss should be in the range of (0, 1) in the training phase.

**Comment by youdonny** [comment]
During the training, configer.get('phase') is "train".

**Comment by iGuaZi** [comment]
During training, the predictions [B, N, (dx, dy, dw, dh, conf, cls_scores)] output by yolo3 model should also be sigmoided, except for dw and dh, isn't it? Since they will later go to BCE loss which requires its input arguments in the range of (0, 1).

**Comment by youdonny** [comment]
self.configer.get('phase') != 'debug'  is True during traing, so they will be sigmoided.
