### ISSUE TITLE
About Quick Start

### ISSUE THREAD

**Issue by Seanlocked** [donnyyou/torchcv#105]
I have done the step git clone https://github.com/donnyyou/torchcv.git to the Cloud Server.
and then run the order: pip3 install -r requirements.txt
when I went to the next step : cd extensions
it returned me this error
(base) root@beeadf295ca5:~/code/torchcv# cd extensions
-bash: cd: extensions: 没有那个文件或目录
So I check the Code and I didn't find the file named extensions
is there something i miss to do?

**Comment by donnyyou** [comment]
Sorry, I have changed the directory to "exts".

**Comment by Seanlocked** [comment]
> Sorry, I have changed the directory to "exts".

Thanks for ur reply! It's my careless so that i miss the abbreviation “exts”
