### ISSUE TITLE
where is the pretrained.pth file?

### ISSUE THREAD

**Issue by iamryanchia** [donnyyou/torchcv#110]
In the .sh file, I find a parameter `PRETRAINED_MODEL` refering to a pretrained file. But I don't find this file in repo. So where is the pretrained.pth file?

**Comment by donnyyou** [comment]
model_urls = {
    'resnet18': 'http://sceneparsing.csail.mit.edu/model/pretrained_resnet/resnet18-imagenet.pth',
    'resnet50': 'http://sceneparsing.csail.mit.edu/model/pretrained_resnet/resnet50-imagenet.pth',
    'resnet101': 'http://sceneparsing.csail.mit.edu/model/pretrained_resnet/resnet101-imagenet.pth'
}

**Comment by iamryanchia** [comment]
@donnyyou Sorry for my inexplicit expression. I don't find the `ssd_vgg16_caffe_pretrained.pth`. Thank you!

**Comment by iamryanchia** [comment]
Oh, I find this in the table's link of `readme.md`. Maybe, you should note it. Thank you!
