### ISSUE TITLE
assert isinstance(dc, DataContainer), type(dc) AssertionError: <class 'torch.Tensor'> when running test

### ISSUE THREAD

**Issue by jerryzhou3** [donnyyou/torchcv#111]
Traceback (most recent call last):
  File "main.py", line 185, in <module>
    Controller.test(runner)
  File "/home/jerry/torchcv/runner/tools/controller.py", line 81, in test
    runner.test(test_dir, out_dir)
  File "/home/jerry/torchcv/runner/seg/fcn_segmentor_test.py", line 48, in test
    total_logits = self.ss_test(data_dict)
  File "/home/jerry/torchcv/runner/seg/fcn_segmentor_test.py", line 85, in ss_test
    data_dict = self.blob_helper.get_blob(in_data_dict, scale=1.0)
  File "/home/jerry/torchcv/runner/tools/blob_helper.py", line 25, in get_blob
    for image, meta in zip(DCHelper.tolist(data_dict['img']), DCHelper.tolist(data_dict['meta'])):
  File "/home/jerry/torchcv/tools/helper/dc_helper.py", line 19, in tolist
    assert isinstance(dc, DataContainer), type(dc)
AssertionError: <class 'torch.Tensor'>

When I run test on my own dataset, the error is thrown.

**Comment by jerryzhou3** [comment]
Seg deeplab on resnet50 is used

**Comment by donnyyou** [comment]
How many GPUs do you use for testing? Could you show me your test command?

**Comment by jerryzhou3** [comment]
I'm using single GPU for testing.
Here's the full log:
bash run_fs_pspnet_canteen_seg.sh val psp
Fri Oct 25 15:33:19 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.87.01    Driver Version: 418.87.01    CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 207...  On   | 00000000:01:00.0 Off |                  N/A |
| N/A   47C    P0    32W /  N/A |    301MiB /  7952MiB |     27%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1309      G   /usr/lib/xorg/Xorg                           127MiB |
|    0      1493      G   /usr/bin/gnome-shell                         171MiB |
+-----------------------------------------------------------------------------+
2019-10-25 15:33:20,892 INFO    [main.py, 161] BN Type is batchnorm.
2019-10-25 15:33:20,893 INFO    [main.py, 162] Config Dict: {
  "dataset": "canteen",
  "task": "seg",
  "method": "fcn_segmentor",
  "data": {
    "image_tool": "cv2",
    "input_mode": "BGR",
    "num_classes": 2,
    "label_list": [
      1,
      2
    ],
    "data_dir": "/home/jerry/dataset/rice_data/rice_torchcv_resized",
    "workers": 8,
    "mean_value": [
      81,
      87,
      93
    ],
    "normalize": {
      "div_value": 1.0,
      "mean": [
        80.6669,
        86.8789,
        93.0238
      ],
      "std": [
        1.0,
        1.0,
        1.0
      ]
    },
    "tag": null,
    "include_val": false,
    "drop_last": false
  },
  "train": {
    "batch_size": 8,
    "aug_trans": {
      "trans_seq": [
        "random_resize",
        "random_crop",
        "random_brightness",
        "random_hflip"
      ],
      "random_brightness": {
        "ratio": 1.0,
        "shift_value": 10
      },
      "random_hflip": {
        "ratio": 0.5,
        "swap_pair": []
      },
      "random_resize": {
        "ratio": 1.0,
        "method": "random",
        "scale_range": [
          0.5,
          2.0
        ],
        "aspect_range": [
          0.9,
          1.1
        ]
      },
      "random_crop": {
        "ratio": 1.0,
        "crop_size": [
          321,
          321
        ],
        "method": "random",
        "allow_outside_center": false
      }
    },
    "data_transformer": {
      "size_mode": "fix_size",
      "input_size": [
        400,
        400
      ],
      "align_method": "only_pad",
      "pad_mode": "random"
    }
  },
  "val": {
    "batch_size": 4,
    "aug_trans": {
      "trans_seq": []
    },
    "data_transformer": {
      "size_mode": "fix_size",
      "input_size": [
        400,
        400
      ],
      "align_method": "only_pad"
    }
  },
  "test": {
    "aug_trans": {
      "trans_seq": []
    },
    "batch_size": 4,
    "data_transformer": {
      "size_mode": "none"
    },
    "mscrop_test": {
      "scale_search": [
        0.75,
        1.0,
        1.25
      ],
      "crop_stride_ratio": 0.667,
      "crop_size": [
        321,
        321
      ]
    },
    "ms_test": {
      "scale_search": [
        0.75,
        1.0,
        1.25
      ]
    },
    "mode": "ss_test",
    "test_dir": "/home/jerry/rice_data/rice_torchcv_resized/val/image",
    "out_dir": "val"
  },
  "details": {
    "color_list": [
      [
        0,
        0,
        0
      ],
      [
        0,
        0,
        128
      ]
    ]
  },
  "network": {
    "backbone": "deepbase_resnet50_dilated8",
    "multi_grid": [
      1,
      1,
      1
    ],
    "model_name": "pspnet",
    "norm_type": "batchnorm",
    "stride": 8,
    "checkpoints_name": "fs_pspnet_canteen_segpsp",
    "checkpoints_dir": "./checkpoints/seg/canteen",
    "checkpoints_root": null,
    "syncbn": false,
    "pretrained": null,
    "resume": "./checkpoints/seg/canteen/fs_pspnet_canteen_segpsp_latest.pth",
    "resume_strict": true,
    "resume_continue": false,
    "resume_val": false,
    "gather": true,
    "distributed": false
  },
  "solver": {
    "lr": {
      "base_lr": 0.01,
      "metric": "iters",
      "lr_policy": "lambda_poly",
      "lambda_poly": {
        "power": 0.9
      },
      "lambda_range": {
        "max_power": 2.0
      },
      "bb_lr_scale": 1.0,
      "nbb_mult": 1.0
    },
    "optim": {
      "optim_method": "sgd",
      "sgd": {
        "weight_decay": 0.0005,
        "momentum": 0.9,
        "nesterov": false
      }
    },
    "display_iter": 50,
    "save_iters": 1000,
    "test_interval": 1000,
    "max_iters": 40000,
    "max_epoch": null,
    "save_epoch": null
  },
  "loss": {
    "loss_type": "dsnce_loss",
    "loss_weights": {
      "ce_loss": {
        "ce_loss": 1.0
      },
      "dsnce_loss": {
        "ce_loss": 1.0,
        "dsn_ce_loss": 0.4
      },
      "dsnohemce_loss": {
        "ohem_ce_loss": 1.0,
        "dsn_ce_loss": 0.4
      }
    },
    "params": {
      "ce_loss": {
        "weight": null,
        "reduction": "mean",
        "ignore_index": -1
      },
      "ohem_ce_loss": {
        "weight": null,
        "reduction": "mean",
        "ignore_index": -1,
        "thresh": 0.7,
        "minkeep": 100000
      }
    }
  },
  "config_file": "configs/seg/canteen/base_fcn_canteen_seg.conf",
  "phase": "test",
  "gpu": [
    0
  ],
  "logging": {
    "log_level": "info",
    "log_format": "%(asctime)s %(levelname)-7s %(message)s"
  },
  "seed": null,
  "cudnn": true,
  "local_rank": 0,
  "project_dir": "/home/jerry/torchcv"
}
2019-10-25 15:33:21,281 INFO    [runner_helper.py, 63] Resuming from ./checkpoints/seg/canteen/fs_pspnet_canteen_segpsp_latest.pth
2019-10-25 15:33:25,068 INFO    [controller.py, 67] Testing start...
2019-10-25 15:33:25,068 INFO    [controller.py, 75] Test directory:/home/jerry/rice_data/rice_torchcv_resized/val/image
2019-10-25 15:33:25,068 INFO    [controller.py, 76] Output directory:/home/jerry/torchcv/results/seg/canteen/fs_pspnet_canteen_segpsp/val
2019-10-25 15:33:25,280 INFO    [blob_helper.py, 25] test meta
2019-10-25 15:33:25,280 INFO    [blob_helper.py, 27] test img
Traceback (most recent call last):
  File "main.py", line 185, in <module>
    Controller.test(runner)
  File "/home/jerry/torchcv/runner/tools/controller.py", line 81, in test
    runner.test(test_dir, out_dir)
  File "/home/jerry/torchcv/runner/seg/fcn_segmentor_test.py", line 48, in test
    total_logits = self.ss_test(data_dict)
  File "/home/jerry/torchcv/runner/seg/fcn_segmentor_test.py", line 85, in ss_test
    data_dict = self.blob_helper.get_blob(in_data_dict, scale=1.0)
  File "/home/jerry/torchcv/runner/tools/blob_helper.py", line 28, in get_blob
    data_list_img = DCHelper.tolist(data_dict['img'])
  File "/home/jerry/torchcv/tools/helper/dc_helper.py", line 18, in tolist
    assert isinstance(dc, DataContainer), type(dc)
AssertionError: <class 'torch.Tensor'>
2019-10-25 15:33:25,887 INFO    [seg_evaluator.py, 51] Evaluate 0 images
/home/jerry/torchcv/metric/seg/seg_running_score.py:37: RuntimeWarning: invalid value encountered in double_scalars
  acc = np.diag(hist).sum() / hist.sum()
/home/jerry/torchcv/metric/seg/seg_running_score.py:38: RuntimeWarning: invalid value encountered in true_divide
  acc_cls = np.diag(hist) / hist.sum(axis=1)
/home/jerry/torchcv/metric/seg/seg_running_score.py:39: RuntimeWarning: Mean of empty slice
  acc_cls = np.nanmean(acc_cls)
/home/jerry/torchcv/metric/seg/seg_running_score.py:40: RuntimeWarning: invalid value encountered in true_divide
  iu = np.diag(hist) / (hist.sum(axis=1) + hist.sum(axis=0) - np.diag(hist))
/home/jerry/torchcv/metric/seg/seg_running_score.py:41: RuntimeWarning: Mean of empty slice
  mean_iu = np.nanmean(iu)
/home/jerry/torchcv/metric/seg/seg_running_score.py:42: RuntimeWarning: invalid value encountered in true_divide
  freq = hist.sum(axis=1) / hist.sum()
/home/jerry/torchcv/metric/seg/seg_running_score.py:43: RuntimeWarning: invalid value encountered in greater
  fwavacc = (freq[freq > 0] * iu[freq > 0]).sum()
2019-10-25 15:33:25,888 INFO    [seg_evaluator.py, 52] Class mIOU: {0: nan, 1: nan}
2019-10-25 15:33:25,888 INFO    [seg_evaluator.py, 53] mIOU: nan
2019-10-25 15:33:25,889 INFO    [seg_evaluator.py, 54] Pixel ACC: nan

**Comment by jerryzhou3** [comment]
My training session works well

**Comment by donnyyou** [comment]
I see. I will fix it today!

**Comment by jerryzhou3** [comment]
Thank you!

**Comment by donnyyou** [comment]
bug fixed!
