### ISSUE TITLE
关于SFNet中Flow Field作用于Low Resolution Feature的细节问题

### ISSUE THREAD

**Issue by Legolas970424** [donnyyou/torchcv#149]
![image](https://user-images.githubusercontent.com/22142026/85511645-7d48e680-b62b-11ea-82bd-18eae5fd4148.png)
你好，请问在这一步进行操作的图像size是Low Resolution 还是High Resolution呢？
![image](https://user-images.githubusercontent.com/22142026/85511740-ad908500-b62b-11ea-865b-d264fd3a358c.png)
Flow Field作用于图像，Field是否需要和该图像的size保持一致？我不太理解这一步的细节，冒昧请教下。

**Comment by Aktcob** [comment]
size不需要保持一致，size实际上是被采样图像的2倍，就可以实现放大图像功能
