### ISSUE TITLE
Question about the implementation of the AlignModule in SFNet

### ISSUE THREAD

**Issue by veizgyauzgyauz** [donnyyou/torchcv#157]
Hi! Thanks for sharing such a great project!
As described in the paper, the low feature and the warped high feature will be sumed up in the Flow Alignment Module. But in the class [AlignModule](https://github.com/donnyyou/torchcv/blob/master/model/seg/nets/sfnet.py), the warped high feature is returned without summation. Could you tell me the reason? Besides, have you done any ablation study about the fusion strategy of the low feature and the warped high feature such as summation, multiplication or none? Thank you so much!

**Comment by lxtGH** [comment]
FAM is based on FPN design where summation is the default design. The main point is we improve the simple upsampling process with learned flow field.
