### ISSUE TITLE
DataParallel leads to Error of Cifar10 classification?

### ISSUE THREAD

**Issue by LuffyDai** [donnyyou/torchcv#24]
I try to do the task of classification of Cifar10 using multiple GPUs. I run the script for this, it leads to an error during calculating the loss as follows:

![捕获](https://user-images.githubusercontent.com/30642162/54526749-af908080-49b2-11e9-9a46-0f2c49978eae.JPG)

However, when I set a single gpu , it works fine. How to fix it?

**Comment by donnyyou** [comment]
I have seemly fix it yesterday. And you could run "git pull origin master".

**Comment by donnyyou** [comment]
Gather before computing loss could lead to this error. https://github.com/youansheng/torchcv/blob/91a0c9363b96632f209d0a471245e98addddd315/methods/cls/image_classifier.py#L128 You could easily fix it.

**Comment by LuffyDai** [comment]
It works! Thank u!
