### ISSUE TITLE
Can't download Semantic Segmentation trained models

### ISSUE THREAD

**Issue by Solomon1588** [donnyyou/torchcv#29]
When I try to download trained models of DeepLabv3, there is a 404 error. Is there anything wrong to the hyperlink? Hope this problem to be corrected, THX :D

**Comment by donnyyou** [comment]
Sorry, I have deleted the trained model. And you could train DeepLabv3 easily with the [scripts](https://github.com/youansheng/torchcv/blob/master/scripts/seg/cityscapes/run_fs_deeplabv3_cityscapes_seg.sh).

**Comment by charlotte12l** [comment]
@donnyyou  Sorry, using your scripts, I can only achieve about 0.682 mIOU while you report 0.7913, did you modify the configure file?  Thanks!

**Comment by donnyyou** [comment]
Have you loaded the imagenet pretrained model？Could you show me your logfile！email me！

**Comment by donnyyou** [comment]
model_urls = {
    'resnet18': 'http://sceneparsing.csail.mit.edu/model/pretrained_resnet/resnet18-imagenet.pth',
    'resnet50': 'http://sceneparsing.csail.mit.edu/model/pretrained_resnet/resnet50-imagenet.pth',
    'resnet101': 'http://sceneparsing.csail.mit.edu/model/pretrained_resnet/resnet101-imagenet.pth'
}

**Comment by donnyyou** [comment]
If you need any further assistance, please do not hesitate to contact me! @charlotte12l
