### ISSUE TITLE
yolov3在coco2017数据集上跑出错

### ISSUE THREAD

**Issue by qiangruoyu** [donnyyou/torchcv#35]
作者你好，看资料应该是北京大学的，中文肯定是好的，我就用中文了。
我想用yolov3来跑coco2017的数据，看项目的结构需要写一个scripts文件，我也写了scripts文件。但是在加了之后开始训练的时候出现了错误。
scripts文件
#!/usr/bin/env bash

nvidia-smi
PYTHON="python"

export PYTHONPATH="/home/dezheng/work/torchcv":$PYTHONPATH

cd ../../../

DATA_DIR="/home/dezheng/work/torchcv/data/torchcv_coco"
MODEL_NAME="yolov3"
LOSS_TYPE="yolov3loss"
CHECKPOINTS_NAME="yolov3_darknet_coco_det"$2
PRETRAINED_MODEL="./pretrained_models/yolov3_darknet_caffe_pretrained.pth"
HYPES_FILE='hypes/det/coco/yolov3_darknet_coco_det.json'

LOG_DIR="./log/det/coco/"
LOG_FILE="${LOG_DIR}${CHECKPOINTS_NAME}.log"

if [[ ! -d ${LOG_DIR} ]]; then
    echo ${LOG_DIR}" not exists!!!"
    mkdir -p ${LOG_DIR}
fi

if [[ "$1"x == "train"x ]]; then
  ${PYTHON} -u main.py --hypes ${HYPES_FILE} --phase train --log_to_file n --gpu 0 --cudnn n \
                       --data_dir ${DATA_DIR} --loss_type ${LOSS_TYPE} --model_name ${MODEL_NAME} \
                       --checkpoints_name ${CHECKPOINTS_NAME} --pretrained ${PRETRAINED_MODEL}  2>&1 | tee ${LOG_FILE}

最后报错如下：
Traceback (most recent call last):
  File "main.py", line 186, in <module>
    runner = method_selector.select_det_method()
  File "/home/dezheng/work/torchcv/methods/method_selector.py", line 93, in select_det_method
    return DET_METHOD_DICT[key](self.configer)
  File "/home/dezheng/work/torchcv/methods/det/yolov3.py", line 35, in __init__
    self.det_data_loader = DataLoader(configer)
  File "/home/dezheng/work/torchcv/datasets/det/data_loader.py", line 23, in __init__
    self.aug_train_transform = pil_aug_trans.PILAugCompose(self.configer, split='train')
  File "/home/dezheng/work/torchcv/datasets/tools/pil_aug_transforms.py", line 1187, in __init__
    self.transforms[trans] = PIL_AUGMENTATIONS_DICT[trans](**aug_trans[trans])
TypeError: __init__() got an unexpected keyword argument 'center_jitter'
这个怎么改呢？

**Comment by donnyyou** [comment]
I'll check it and update soon. Maybe you could simply remove the unexpected keywords in hypes file. I have refactored the code many times, so there may exist some little bugs.

**Comment by qiangruoyu** [comment]
> I'll check it and update soon. Maybe you could simply remove the unexpected keywords in hypes file. I have refactored the code many times, so there may exist some little bugs.

I'm trying to get rid of unexpected keywords,But there's a new problem.I was afraid that I had made a mistake, so there was a series of problems.In the end, I came to ask for help.

**Comment by donnyyou** [comment]
I have updated the hypes.

**Comment by qiangruoyu** [comment]
> I have updated the hypes.

That problem just disappeared, but there's a new one.

2019-04-15 11:46:11,217 WARNING [module_helper.py, 137] ./pretrained_models/yolov3_darknet_caffe_pretrained.pth not exists.
2019-04-15 11:46:11,218 ERROR   [configer.py, 69] darknet_yolov3.py, 38 KeyError: ('gt', 'anchors_list')

**Comment by donnyyou** [comment]
Replace the 'gt' with 'anchor', because I have changed the key str.

**Comment by donnyyou** [comment]
I am refactoring all the code. All the little bugs will be fixed later if you could wait for a few days.

**Comment by qiangruoyu** [comment]
ok.This framework is the most complete pytorch-based framework I've ever seen. 
I'm looking forward to it.

**Comment by qiangruoyu** [comment]
> I am refactoring all the code. All the little bugs will be fixed later if you could wait for a few days.

Has this problem been solved?
