### ISSUE TITLE
How to train the icnet model in the folder（demos/personseg/models）

### ISSUE THREAD

**Issue by 853498747** [donnyyou/torchcv#40]
Excuese me ,the code 'person_segmentor.py' in demos folder needs  pretrained model in the following code :
  'fabby_model': './model/ICNet32Photo640x480_iter_310000.pth',
  'trimap_model': './model/trimap_icnet32SimpleV2_iter_120000.pth',
  'mat_model': './model/trimap_icnet32SimpleV2_matting_iter_120000.pth'

How can i get the pretrained model or how to train the model ?
thankyou

**Comment by donnyyou** [comment]
You could train with the person segmentation dataset that you could find on the internet.  It's only the combination of normal segmentation task and image matting.

**Comment by donnyyou** [comment]
If you are interested in this demo. You could contact me with email. My email address is youansheng@pku.edu.cn.
