### ISSUE TITLE
simultaneous object detection and human pose estimation

### ISSUE THREAD

**Issue by sophia-wright-blue** [donnyyou/torchcv#5]
this repo is an amazing idea! i have a question about its usage - would it be possible to do simultaneous object detection and human pose estimation?

i'd like to test on an image and use SSD for object detection and OpenPose for human pose estimation.

if its possible, i'd greatly appreciate the steps/code to accomplish this.

thanks,

**Comment by youdonny** [comment]
It's easy to accomplish this! I will show some examples and please keep continuous attention!

**Comment by sophia-wright-blue** [comment]
thanks for replying @CVBox , looking forward to your examples!
