### ISSUE TITLE
A bug when doing bash xxx.sh val tag

### ISSUE THREAD

**Issue by ruotianluo** [donnyyou/torchcv#53]
https://github.com/donnyyou/torchcv/blob/master/methods/seg/fcn_segmentor_test.py#L172

Should [-1] be removed?

res[-1] has only three dimensions.

**Comment by ruotianluo** [comment]
Never mind. This is because PSPNet have two outputs and mine only have one output.

**Comment by ruotianluo** [comment]
While I'm thinkg if res[-1] should be res['out'], there is another bug occured.

> File "main.py", line 203, in <module>
>     Controller.test(runner)
>   File "/share/data/vision-greg/rluo/torchcv2/methods/tools/controller.py", line 78, in test
>     runner.test(test_dir, out_dir)
>   File "/share/data/vision-greg/rluo/torchcv2/methods/seg/fcn_segmentor_test.py", line 57, in test
>     total_logits = self.mscrop_test(data_dict, params_dict=self.configer.get('test', 'mscrop_test'))
>   File "/share/data/vision-greg/rluo/torchcv2/methods/seg/fcn_segmentor_test.py", line 122, in mscrop_test
>     data_dict = self.blob_helper.get_blob(in_data_dict, scale=scale)
>   File "/share/data/vision-greg/rluo/torchcv2/methods/tools/blob_helper.py", line 27, in get_blob
>     b, c, h, w = image.size()


Seems it's caused by https://github.com/donnyyou/torchcv/blob/master/utils/helpers/dc_helper.py#L23

**Comment by donnyyou** [comment]
I have fixed this bug & tested it with 4 GPUs.
