### ISSUE TITLE
pytorch1.1 running error

### ISSUE THREAD

**Issue by shuxp** [donnyyou/torchcv#58]
It seems that torchCV is running with pytorch1.0. But with pytorch1.1 I got error "RuntimeError: CUDA error: an illegal memory access was encountered" during training. Could you help me with this? I don't want to use pytorch1.0....

**Comment by donnyyou** [comment]
Thanks for your issue! I will check & update it in this week.

**Comment by donnyyou** [comment]
I have tested successfully with pytorch 1.1. Could you show me the full error log and the scripts you run?

**Comment by fnwkqwan** [comment]
> I have tested successfully with pytorch 1.1. Could you show me the full error log and the scripts you run?

when I ran the faster-rcnn train, I got the error"RuntimeError: cuda runtime error (77) : an illegal memory access was encountered at /opt/conda/conda-bld/pytorch_1549636813070/work/aten/src/THC/generated/../THCReduceAll.cuh:317"; but no error when     I ran the ssd300 train. How could I do for this?
