### ISSUE TITLE
SSD512-->SSDHead-->self.feature6

### ISSUE THREAD

**Issue by zllrunning** [donnyyou/torchcv#7]
## Two questions:

1. self.feature6 does not have Relu layers.
```
        self.feature6 = nn.Sequential(
            nn.Conv2d(256, 128, kernel_size=1, stride=1),
            nn.Conv2d(128, 256, kernel_size=4, stride=1, padding=1))
```
Is it supposed to be like this?
```
        self.feature6 = nn.Sequential(
            nn.Conv2d(256, 128, kernel_size=1, stride=1),
            nn.ReLU(),
            nn.Conv2d(128, 256, kernel_size=4, stride=1, padding=1))
            nn.ReLU(),
```

2.  The input feature's size to this layer is `torch.Size([batch_size, 256, 2, 2])`, but why use ` kernel_size=4`  instead of `kernel_size=2` ?

Thank you again in advance for your great help!

**Comment by youansheng** [comment]
Thanks! You're right!
1. It's really a bug that I have ignored. Thanks again!!!
2. You are right, too.
