### ISSUE TITLE
configure file of openpose?

### ISSUE THREAD

**Issue by zhao1f** [donnyyou/torchcv#72]
Hi, I think there exists a lot of mismatches of the open_pose_vgg_19.conf and the modules of your code, I revised most of them but still faces a lot of undefined ones.
Most of them are key Error and some of them may come from the directory of exts/tools/.

I was wondering if there is a newly-updated configuration file of open_pose.  Appreciate for your updates.

**Comment by donnyyou** [comment]
Sorry, I will soon update the config file this week.
