### ISSUE TITLE
怎么在window上编译使用roi_pool

### ISSUE THREAD

**Issue by saladjay** [donnyyou/torchcv#81]
使用git去编译exts文件夹下的make.sh,在align和pool文件夹下出现build文件夹。之后应该做什么操作才能正常使用import exts.ops.roi_align。现在导入import exts.ops.roi_align会出现

1 from torch.autograd import Function
      2 
----> 3 from .. import roi_align_cuda
      4 
      5 

ImportError: cannot import name 'roi_align_cuda'

**Comment by donnyyou** [comment]
不能在windows下使用。
